# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d347c7b5c61dedc140f490a7da8a074a9acaf30e77e9a20df03314dc4d4462866a6c2124c3899a55133ad8acc18ba65c634b62988d60b26abbb3d29918b308

test:
  secret_key_base: 518db7281c1701828cc9e16d2441d783555600b52e86e83f06876bce4c91f435f980c91ff364e5fbeef410aacf6ee7a112139bff35884a7bc5ea8b3eecdad2fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
